name: Check the source code
on:
  pull_request:
    branches:
      - develop
      - main
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Prettier
        run: npm run prettier
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test